import type { NextPage } from 'next';
import { useTheme } from 'next-themes';
import Head from 'next/head';

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">The current theme is: {theme}</h1>
        <button className="btn btn-primary" onClick={() => setTheme('light')}>
          Light
        </button>
        <button className="btn btn-secondary" onClick={() => setTheme('dark')}>
          Dark
        </button>
        <button className="btn btn-accent" onClick={() => setTheme('system')}>
          System
        </button>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
