import Head from 'next/head';
import { Footer } from './footer/footer';
import { Header } from './header/header';

type Props = {
  children: React.ReactNode;
};

export default function Layout({ children }: Props) {
  return (
    <div className="bg-base-300">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-7/12 m-auto h-screen">{children}</main>
      <Footer />
    </div>
  );
}
